# Generated by Django 2.1 on 2019-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190624_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='postratings',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
