# Generated by Django 2.1 on 2019-06-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_postratings_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postratings',
            old_name='count',
            new_name='rater_count',
        ),
        migrations.RemoveField(
            model_name='postratings',
            name='user',
        ),
    ]
