# Generated by Django 2.1 on 2019-06-26 06:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190624_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postratings',
            name='rater_count',
        ),
        migrations.RemoveField(
            model_name='postratings',
            name='total',
        ),
        migrations.AddField(
            model_name='postratings',
            name='rate',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='postratings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postratings',
            name='average',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='postratings',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Post'),
        ),
    ]
